"""increased character limits for inputs on db

Revision ID: 51bd1a3fd72b
Revises: a68b18376638
Create Date: 2024-05-31 11:01:53.393280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bd1a3fd72b'
down_revision = 'a68b18376638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drink', schema=None) as batch_op:
        batch_op.alter_column('drink_name',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('drink_glass',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('drink_ice',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('drink_method',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('drink_garnish',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drink', schema=None) as batch_op:
        batch_op.alter_column('drink_garnish',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
        batch_op.alter_column('drink_method',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('drink_ice',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('drink_glass',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
        batch_op.alter_column('drink_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###
