"""baseline

Revision ID: initial
Revises: 
Create Date: 2024-06-13 16:00:00.000000

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('drink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink_image', sa.String(length=255), nullable=True),
    sa.Column('drink_name', sa.String(length=255), nullable=True),
    sa.Column('drink_glass', sa.String(length=255), nullable=False),
    sa.Column('drink_ice', sa.String(length=255), nullable=False),
    sa.Column('drink_method', sa.String(length=255), nullable=False),
    sa.Column('drink_ingredients', sa.Text(), nullable=False),
    sa.Column('drink_garnish', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drink')
    op.drop_table('user')
    # ### end Alembic commands ###
